name: servicemon

channels:
    - astropy

dependencies:
    - python>=3.6
    - astropy
    - astroquery
    - Cython
    - matplotlib
    - numpy
    - requests
    - sphinx-astropy
#   - pip:
#       - dependency_from_pip
